---
title: "Bethesda IV - Przygotowanie zbioru danych"
author: "Piotr Wiśniewski, Gosia Struk-Panfil, Ewa Zalewska"
date:  "`r format(Sys.time(), '%e %b %Y, godz. %H:%M')`"
output: html_document
---

```{r, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r setup, include=FALSE}

library(ggplot2)
library(dplyr)
library(readr)
library(ggpubr)
library(lubridate)
library(mice)


bethIV <- read_delim("beth4_EZ_v2.csv", delim = ";", 
    escape_double = FALSE,locale = locale(decimal_mark = ","), trim_ws = TRUE)

# Usunięcie wierszy z brakami danych (więcej niż 11 braków w danych)
bethIV <- bethIV %>%
  filter(rowSums(is.na(.)) <= 11)

# Formatowanie wartości w kolumnach
bethIV$data_wyjsciowa <- as.Date(bethIV$data_wyjsciowa, format = "%Y-%m-%d")
bethIV$data_koncowa <- as.Date(bethIV$data_koncowa, format = "%Y-%m-%d")
bethIV$data_urodzenia <- as.Date(bethIV$data_urodzenia, format = "%Y-%m-%d")
bethIV$data_operacji <- as.Date(bethIV$data_operacji, format = "%Y-%m-%d")
bethIV$wym1 <- as.numeric(bethIV$wym1)
bethIV$wym2 <- as.numeric(bethIV$wym2)
bethIV$wym3 <- as.numeric(bethIV$wym3)
bethIV$wym4 <- as.numeric(bethIV$wym4)
bethIV$wym5 <- as.numeric(bethIV$wym5)
bethIV$wym6 <- as.numeric(bethIV$wym6)

## Dodanie kolumny z wiekiem pacjentów w momencie koncowego badania USG
bethIV <- bethIV %>%
  mutate(
    wiek = time_length(interval(data_urodzenia, data_koncowa), unit = "years")
  )

## Dodanie kolumny z różnicą w dniach używając mutate
bethIV <- bethIV %>%
  mutate(
    czas_nadzoru_lata = time_length(interval(data_wyjsciowa, data_koncowa), unit = "years")
  )

bethIV %>%
  get_summary_stats(czas_nadzoru_lata, type = "common")

# Usunięcie wszystkich wartości, które mają różnicę między pierwszą a drugą obserwacją mniejszą niż dwa lata
bethIV_2_lata <- bethIV %>%
  filter(czas_nadzoru_lata >= 2)

bethIV_2_lata %>%
  get_summary_stats(czas_nadzoru_lata, type = "common")

```

# algorytm MICE 
``` {r echo=FALSE}
kolumny_do_imputacji <- c("wym1", "wym2", "wym3", "wym4", "wym5", "wym6")
dane_subset <- bethIV_2_lata[, kolumny_do_imputacji]

imputacja <- mice(dane_subset, m = 5, method = 'pmm', seed = 123)

dane_imputowane <- complete(imputacja, 1)

bethIV_2_lata[, kolumny_do_imputacji] <- dane_imputowane

summary(bethIV_2_lata)

```



## Uszereguj wartosci w kolumnach od najwieszej do najmniejszej:
### A-C wymiary od największego do najmniejszgo na początku obserwacji:
### D-F wymiary od największego do najmniejszego na koniec obserwacji:
``` {r echo=FALSE}
bethIV_2_lata <- mutate(bethIV_2_lata, wymA = pmax(bethIV_2_lata$wym1, bethIV_2_lata$wym2, bethIV_2_lata$wym3))
bethIV_2_lata <- mutate(bethIV_2_lata, wymB = apply(bethIV_2_lata[, c("wym1", "wym2", "wym3")], 1, function(x) sort(x)[2]))
bethIV_2_lata <- mutate(bethIV_2_lata, wymC = pmin(bethIV_2_lata$wym1, bethIV_2_lata$wym2, bethIV_2_lata$wym3))

bethIV_2_lata <- mutate(bethIV_2_lata, wymD = pmax(bethIV_2_lata$wym4, bethIV_2_lata$wym5, bethIV_2_lata$wym6))
bethIV_2_lata <- mutate(bethIV_2_lata, wymE = apply(bethIV_2_lata[, c("wym4", "wym5", "wym6")], 1, function(x) sort(x)[2]))
bethIV_2_lata <- mutate(bethIV_2_lata, wymF = pmin(bethIV_2_lata$wym4, bethIV_2_lata$wym5, bethIV_2_lata$wym6))

```


``` {r echo=FALSE}
bethIV_2_lata <- bethIV_2_lata %>% 
  mutate(
    sprawdzenie_szeregu = ifelse((wymB > wymA) | (wymC > wymB) | (wymC > wymA) | (wymE > wymD) | (wymF > wymE) | (wymF > wymD), 1, 0)
  )

```

# Definicja progresji wielkości guzka

```{r}
bethIV_2_lata <- bethIV_2_lata %>%
  mutate(
    progresja = ifelse((wymD - wymA) > 2 & (wymB - wymE) > 2 | (wymD - wymA) > 2 & (wymC - wymF) > 2 | (wymC - wymF) > 2 & (wymB - wymE) > 2 | (wymD - wymA) > 2 & (wymB - wymE) > 2 & (wymC - wymF) > 2, 1, 0)
  )
```


# Zapisz lokalnie zbiór danych przeznaczony do analizy 
```{r}
plik_dane_do_analizy <- "bethIV_2_lata.RDS"
saveRDS(bethIV_2_lata, plik_dane_do_analizy)
```

