# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths: ['**.Rmd']
  workflow_dispatch:

name: render-rmarkdown.yaml

permissions: read-all

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
      
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render all Rmd files (starting with b4pte_1_przygotowanie_danych.Rmd)
        run: |
          mkdir -p docs
      
          echo "Rendering b4pte_1_przygotowanie_danych.Rmd"
          Rscript -e "rmarkdown::render('b4pte_1_przygotowanie_danych.Rmd', output_dir = 'docs')"
      
          echo "Rendering remaining Rmd files"
          find . -name '*.Rmd' ! -name 'b4pte_1_przygotowanie_danych.Rmd' -print0 | while IFS= read -r -d '' f; do
            echo "Rendering $f"
            Rscript -e "rmarkdown::render('$f', output_dir = 'docs')"
          done
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add docs
          git commit -m 'Rendered Rmd files to docs/' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

      - name: Generate index.html with links to rendered reports
        run: |
          echo "<html><head><meta charset='UTF-8'><title>Rendered Reports</title></head><body>" > docs/index.html
          echo "<h1>Rendered R Markdown Reports</h1><ul>" >> docs/index.html
          for f in docs/*.html; do
            fname=$(basename "$f")
            if [ "$fname" != "index.html" ]; then
              echo "<li><a href=\"$fname\">$fname</a></li>" >> docs/index.html
            fi
          done
          echo "</ul></body></html>" >> docs/index.html