# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths: ['**.Rmd']
  workflow_dispatch:

name: render-rmarkdown.yaml

permissions: read-all

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
      
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/R
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "knitr", "tidyverse", "scales", "ggpubr", "readr", "mice"))'

      - name: Render changed or all Rmd files
        run: |
          mkdir -p docs
          RMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]Rmd$' || true))
          if [ ${#RMD_PATH[@]} -eq 0 ]; then
            echo "No changed Rmds found — rendering all"
            RMD_PATH=(*.Rmd)
          fi
          for f in "${RMD_PATH[@]}"; do
            echo "Rendering $f"
            Rscript -e "rmarkdown::render('$f', output_dir = 'docs')"
          done
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add docs
          git commit -m 'Rendered Rmd files to docs/' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
